modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/skyecodes/IBE-Editor/issues"
logoFile = "logo.png"

[[mods]]
modId = "ibeeditor"
version = "${version}"
displayName = "IBE Editor"
updateJSONURL = "https://raw.githubusercontent.com/skyecodes/IBE-Editor/1.20/forge_update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ibe-editor"
credits = "Emex (logo)"
authors = "skyecodes"
description = "Simple GUI Mod to edit an item, a block or an entity in your current world"

[[dependencies.ibeeditor]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ibeeditor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"